### ISSUE TITLE
Error when using module.

### ISSUE THREAD

**Issue by tedivm** [duritong/puppet-trocla#13]
> Error: /File[/var/lib/puppet/lib]: Failed to generate additional resources using 'eval_generate': Error 400 on SERVER: Permission denied - /etc/puppet/modules/trocla/lib/puppet/parser/functions/trocla_get.rb

**Comment by duritong** [comment]
Looks like the permissions are wrong on your puppetmaster, actually they are wrong within the tarball. Why are filemodes leaking into puppet-module-packages? Questions, over questions... I will release a new version with fixed chmod.

**Comment by tedivm** [comment]
Bump: can I get that repackage? Or at least let me know what permissions should be what so I can correct it on my own?

**Comment by duritong** [comment]
I was travelling and hence was not able to do things earlier.

Anyway, it could have been fixed by just chmod +rX the module on the master.

Nevertheless, the latest version 0.0.8 fixes this issue and also includes the latest PRs to this module.

**Comment by tedivm** [comment]
For the record you don't need the executable bit set, just the read one.

**Comment by duritong** [comment]
Capital X sets it only on directories...

**Comment by tedivm** [comment]
I wasn't referring to your command here- I actually downloaded the package, looked at the new permissions, and saw that you set the executable bits (all of them) on the ruby files, when you just needed to make them readable. 

Go download the package and look for yourself.

**Comment by duritong** [comment]
I did:
```
$ find duritong-trocla-0.0.8/ -type f -ls
171689    4 -rw-rw-r--   1 bla       bla            742 May 24 18:14 duritong-trocla-0.0.8/checksums.json
171688    4 -rw-rw-r--   1 bla       bla            505 May 24 18:06 duritong-trocla-0.0.8/templates/troclarc.yaml.erb
171686    4 -rw-rw-r--   1 bla       bla            504 May 24 18:14 duritong-trocla-0.0.8/metadata.json
171685    4 -rw-rw-r--   1 bla       bla            986 Oct  2  2013 duritong-trocla-0.0.8/manifests/yaml.pp
171684    4 -rw-rw-r--   1 bla       bla            247 Apr  5 19:19 duritong-trocla-0.0.8/manifests/master.pp
171683    4 -rw-rw-r--   1 bla       bla            350 Oct  2  2013 duritong-trocla-0.0.8/manifests/master/ree.pp
171681    4 -rw-rw-r--   1 bla       bla           1585 Apr  4 17:04 duritong-trocla-0.0.8/manifests/config.pp
171679    4 -rw-rw-r--   1 bla       bla           1320 Mar 20  2013 duritong-trocla-0.0.8/lib/puppet/util/trocla_helper.rb
171677    4 -rw-rw-r--   1 bla       bla           2285 Mar 20  2013 duritong-trocla-0.0.8/lib/puppet/parser/functions/trocla_set.rb
171676    4 -rw-r--r--   1 bla       bla            781 Jun  3  2012 duritong-trocla-0.0.8/lib/puppet/parser/functions/trocla_get.rb
171675    4 -rw-rw-r--   1 bla       bla            972 Jun  3  2012 duritong-trocla-0.0.8/lib/puppet/parser/functions/trocla.rb
171670    4 -rw-rw-r--   1 bla       bla           2378 Apr  5 19:20 duritong-trocla-0.0.8/README.md
```
