### ISSUE TITLE
Remove hiera-backend in favor of https://github.com/ZeroPointEnergy/hiera-backend-trocla

### ISSUE THREAD

**Issue by duritong** [duritong/puppet-trocla#17]
This is mainly for @michaelweiser:

So someone else implemented another hiera-backend for trocla: https://github.com/ZeroPointEnergy/hiera-backend-trocla

At first it couldn't do as much as yours, but now as the @ZeroPointEnergy iterated over it again it is feature equivalent with yours. And actually to be honest: it now not only has all the features of your backend, but also addresses a few drawbacks. Like that with your backend, you can only get a password in one specific format for one node, and you can't get both, e.g. a plain and a mysql backend.

Also that imho it makes to sense to maintain 2 backends, I'm actually in favor of removing your backend from this module and within the README of this module and trocla point to @ZeroPointEnergy's module.
Also note that for puppet-server installation we can't distribute the backend anymore using a puppet module, but should do it with a gem. Which is also something that the other module addresses and which is also one of the reasons, why I would like to keep the backend out of the module.

To make the long story short: What are you feelings about removing your code and pointing to the other backend?

I guess it should be too much work of migrating your existing hiera configuration over to the new backend, or keep your backend in an own repository, which you would maintain on your own.

Sorry for that, but I would say this is how iterating works in software development.

**Comment by michaelweiser** [comment]
No prob. I have my code for now in my own module and it works for the project I'm doing. A cursory look over @ZeroPointEnergy's module makes me think that it's conceptually the same and could work almost as a drop-in-replacement for mine. If I have the time I'll try it out for my project.
